name: CI

on:
  push:
    branches:
      - master

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          host: 'windows'
          target: 'desktop'
          install-deps: 'true'
          archives: 'qtbase'
          setup-python: 'false'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make
        run: |
          for /f "delims=" %%d in ( 'vswhere.exe -latest -property installationPath' ) do @( call "%%d\VC\Auxiliary\Build\vcvars64.bat" )
          qmake ${{github.workspace}}\LCTRL.pro
          nmake
          dir /s ${{github.workspace}}\release
        shell: cmd
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{github.workspace}}\release\LCTRL.exe
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install libicu
        run: sudo apt-get install -y libicu-dev
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          host: 'linux'
          target: 'desktop'
          install-deps: 'true'
          archives: 'qtbase'
          setup-python: 'false'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make
        run: |
          qmake ${{github.workspace}}/LCTRL.pro
          make
          tree ${{github.workspace}}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{github.workspace}}/LCTRL
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          host: 'mac'
          target: 'desktop'
          install-deps: 'true'
          archives: 'qtbase'
          setup-python: 'false'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make
        run: |
          qmake ${{github.workspace}}/LCTRL.pro
          make
          ls -R ${{github.workspace}}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{github.workspace}}/LCTRL
