name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          host: 'windows'
          target: 'desktop'
          install-deps: 'true'
          setup-python: 'false'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make
        run: |
          for /f "delims=" %%d in ( 'vswhere.exe -latest -property installationPath' ) do @( call "%%d\VC\Auxiliary\Build\vcvars64.bat" )
          qmake ${{github.workspace}}\LCTRL.pro
          nmake
          cd ${{github.workspace}}\release
          mkdir deploy
          copy LCTRL.exe deploy\LCTRL.exe
          cd deploy
          windeployqt --qmldir ${{github.workspace}} --no-translations --release --compiler-runtime LCTRL.exe
          7z a LCTRL.zip * -r
        shell: cmd
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{github.workspace}}\release\deploy\LCTRL.zip
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: LCTRL.zip
          path: ${{github.workspace}}\release\deploy\LCTRL.zip
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          host: 'mac'
          target: 'desktop'
          install-deps: 'true'
          setup-python: 'false'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make
        run: |
          qmake ${{github.workspace}}/LCTRL.pro
          make
          cd ${{github.workspace}}
          mkdir deploy
          cp LCTRL.app
          ls -a -l -R
          macdeployqt LCTRL -dmg
          ls -a -l -R
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{github.workspace}}/LCTRL
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: LCTRL
          path: ${{github.workspace}}/LCTRL
#   build-linux:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Install Qt
#         uses: jurplel/install-qt-action@v3
#         with:
#           host: 'linux'
#           target: 'desktop'
#           install-deps: 'true'
#           archives: 'qtbase'
#           setup-python: 'false'
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Make
#         run: |
#           qmake ${{github.workspace}}/LCTRL.pro
#           make
#           tree ${{github.workspace}}
#       - name: Release
#         uses: softprops/action-gh-release@v1
#         if: startsWith(github.ref, 'refs/tags/')
#         with:
#           files: ${{github.workspace}}/LCTRL
